
name: Update Build Command in package.json

on:
  pull_request:
    types:
      - closed

jobs:
  update-package-json:
    runs-on: ubuntu-latest

    env:
      BRANCH_CONFIGURATIONS: '{"dev-integration":"dev", "sit-integration":"sit", "uat-integration":"uat", "prod-integration":"prod"}'
      NGKEY: githubActionEnv

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if the branch is valid
        run: |
          BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
          CONFIG_COMMAND=$(echo "$BRANCH_CONFIGURATIONS" | jq -r --arg branch "$BRANCH_NAME" '.[$branch]')
                    
          if [ -z "$CONFIG_COMMAND" ]; then
            echo "The branch is not valid, exiting..."
            exit 0
          fi
          echo "The config to use is $BRANCH_NAME"

      - name: Update Build Configuration
        run: |
          # Replace the line containing "githubActionEnv" with the corresponding configuration
          echo "The config to use is $CONFIG_COMMAND"
          sed "s/$NGKEY/$CONFIG_COMMAND/" js-storefront/test/package.json
          sed -i "s/$NGKEY/$CONFIG_COMMAND/" js-storefront/test/package.json

      - name: Commit and push changes
        run: |
          git config --local user.email "${GITHUB_ACTOR}@github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          cat js-storefront/test/package.json
          git add js-storefront/test/package.json
          git commit -m "Update build configuration in package.json"
          git push
